### ISSUE TITLE
Bug at start: Camera moves to bottom corner of your scene/boundaries.

### ISSUE THREAD

**Issue by aceakle** [Nickk888SAMP/RTSCameraController-Cinemachine#11]
Camera moves to the bottom left corner of your map at start. I was able to band-aid fix this in my project by using a coroutine to wait a sec at start to allow for mouse input to be registered before allowing this method `HandleScreenSideMove()` to be called in the update method.

I also noticed that the camera moves when you have no input, so hit the windows key and the script will lose input and the camera will start moving to the bottom left of the map.

**Comment by Nickk888SAMP** [comment]
Hi there! Thanks for reporting the Issue, is the issues still persisting after ticking Off/Disabling "Allow Screen Side Move"?

**Comment by aceakle** [comment]
The bug is gone when I disable "Allow Screen Side Move". But in my case, I want to allow the screen side move feature so there needs to be something that disables the Screen Side Move for the first few seconds or better yet have the Screen Side Move do nothing when mouse input is null

**Comment by Nickk888SAMP** [comment]
After some testing and digging in code, i found the problem withing the code. The problem probably lies within the GetMouseScreenSide Method which gives me invalid width and height if supplied with a Vector3.zero which is interesting. 
I'll now take a look into fixing it and let you know when a new Version will be published.

I'll also consider adding some Unit Tests so bugs like this won't happen again.

Thanks for reporting the bug!

**Comment by Nickk888SAMP** [comment]
Issue has been fixed, i have made some tests an I've got no issues whatsoever now. It should work now, i've added 2 "safety guards":

1. Variable _currentMousePosition now becomes a default value of the Screen middle position so the system won't send the camera to nirvana anymore on start.
2. The problem with the Windows key and lose input was a Focus problem. If the user is not focused in the game, the mouse position won't be updated so if you loose focus while on the screen sides, you guessed it, Nirvana... I've fixed it by adding a _isFocused variable that stops the Scripts Update while not in Focus. That fixes the problem.

Download the latest version here: https://github.com/Nickk888SAMP/RTSCameraController-Cinemachine/releases

If there's any more issues, please let me know :) Also let me know if the bug is really gone, there's always a chance that i've missed something, though i've made some tests and added Unit Tests which all passed.
